index:
    path: /
    controller: App\Controller\HomeController::index
health:
    path: /health
    controller: App\Controller\HomeController::health
# deploy:
#    path: /deploy
#    controller: App\Controller\HomeController::deploy