name: —Åi-cd-pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Composer install
        run: composer install
      - name: Cache clear
        run: php bin/console cache:clear
      - uses: actions/upload-artifact@v2
        with:
          name: build-project
          path: /home/runner/work/lab67/lab67
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-project
      - name: Unit testing
        run: php ./vendor/bin/phpunit
      - name: Phpstan
        run: php vendor/bin/phpstan analyse -l 9 src
  deploy-staging:
    runs-on: ubuntu-latest
    needs: [build, test]
    environment: staging
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-project
      - uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
