name: Ci-cd-pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check folder
        run: ls -la
      - name: Composer install
        run: composer install
      - name: Cache clear
        run: php bin/console cache:clear
      - name: Check folder
        run: ls -la
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Check folder
        run: ls -la
      - name: Unit tests
        run: ./vendor/bin/phpunit
