name: —Åi-cd-pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Composer install
        run: composer install
      - name: Cache clear
        run: php bin/console cache:clear
      - uses: actions/upload-artifact@v2
        with:
          name: build-project
          path: dist
