name: Ci-cd-pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Composer install
        run: composer install
      - name: Cache clear
        run: php bin/console cache:clear
      - uses: actions/upload-artifact@v2
        with:
          name: build-project
          path: /home/runner/work/lab67/lab67
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
      - name: Check folder
        run: ls -la
      - name: Unit tests
        run: ./vendor/bin/phpunit
