name: —Åi-cd-pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Composer install
        run: composer install
      - name: Cache clear
        run: php bin/console cache:clear
      - name: Go to folder
        run: cd /home/runner/work/lab67/lab67
      - name: Show
        run: ls -la
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Unit testing
        run: php ./vendor/bin/phpunit
      - name: Phpstan
        run: php vendor/bin/phpstan analyse -l 9 src
      - name: Show
        run: ls -la
